# Generated by Django 3.0.5 on 2020-04-16 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcf_website', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['subdepartment', 'number'], name='tcf_website_subdepa_f296bc_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['school'], name='tcf_website_school__d40b59_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['course', 'instructor'], name='tcf_website_course__84da62_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['user'], name='tcf_website_user_id_36b38e_idx'),
        ),
        migrations.AddIndex(
            model_name='subdepartment',
            index=models.Index(fields=['department'], name='tcf_website_departm_85d335_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['review'], name='tcf_website_review__5435a6_idx'),
        ),
    ]
