# Generated by Django 3.0.5 on 2020-04-16 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcf_website', '0002_auto_20200416_0156'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='section',
            index=models.Index(
                fields=[
                    'semester',
                    'course'],
                name='tcf_website_semeste_8d4c29_idx'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(
                fields=['course'],
                name='tcf_website_course__ea693c_idx'),
        ),
    ]
