# Generated by Django 3.0.5 on 2020-04-18 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcf_website', '0003_auto_20200416_0220'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='review',
            name='tcf_website_user_id_36b38e_idx',
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(
                fields=[
                    'user',
                    '-created'],
                name='tcf_website_user_id_0f70cf_idx'),
        ),
    ]
