# Generated by Django 3.0.5 on 2020-04-22 06:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tcf_website', '0005_auto_20200419_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseAverage',
            fields=[
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tcf_website.Course')),
                ('instructor_rating_avg', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('difficulty_avg', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('recommendability_avg', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('hours_per_week_avg', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(168)])),
            ],
        ),
        migrations.CreateModel(
            name='InstructorAverage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor_rating_avg', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('difficulty_avg', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('recommendability_avg', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('hours_per_week_avg', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(168)])),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tcf_website.Course')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tcf_website.Instructor')),
            ],
        ),
        migrations.AddIndex(
            model_name='instructoraverage',
            index=models.Index(fields=['course', 'instructor'], name='tcf_website_course__f874fe_idx'),
        ),
        migrations.AddConstraint(
            model_name='instructoraverage',
            constraint=models.UniqueConstraint(fields=('course', 'instructor'), name='unique average per course and instructor'),
        ),
    ]
