# Based on https://github.com/actions/starter-workflows/blob/main/ci/django.yml
name: Continuous Integration

on:
  pull_request:
    branches:
      - '*'
    paths-ignore:
    - 'docs/**'
  # The following is needed to run tests upon direct push to master
  push:
    branches: [master]
    paths-ignore:
    - 'docs/**'
env:
  PYTHON_TARGET: 3.8
  # Django
  DJANGO_SETTINGS_MODULE: tcf_core.settings.ci
  SECRET_KEY: ${{ secrets.SECRET_KEY }}
  DEBUG: 1
  # database 
  DB_NAME: tcf_db  # arbitrary string
  DB_USER: postgres  # default user
  DB_PASSWORD: postgres  # default password
  DB_HOST: localhost  # required for GitHub Actions
  DB_PORT: 5432  # default port
  # social-auth-app-django
  SOCIAL_AUTH_GOOGLE_OAUTH2_KEY: ${{ secrets.SOCIAL_AUTH_GOOGLE_OAUTH2_KEY }}
  SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET: ${{ secrets.SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET }}
  # elasticsearch
  ES_PUBLIC_API_KEY: ${{ secrets.ES_PUBLIC_API_KEY }}
  ES_COURSE_SEARCH_ENDPOINT: ${{ secrets.ES_COURSE_SEARCH_ENDPOINT }}
  ES_INSTRUCTOR_SEARCH_ENDPOINT: ${{ secrets.ES_INSTRUCTOR_SEARCH_ENDPOINT }}
  ES_COURSE_DOCUMENTS_ENDPOINT: ${{ secrets.ES_COURSE_DOCUMENTS_ENDPOINT }}
  ES_INSTRUCTOR_DOCUMENTS_ENDPOINT: ${{ secrets.ES_INSTRUCTOR_DOCUMENTS_ENDPOINT }}
  ES_PRIVATE_API_KEY: ${{ secrets.ES_PRIVATE_API_KEY }}
  # discord
  DISCORD_URL_BUG: ${{ secrets.DISCORD_URL_BUG }}
  DISCORD_URL_FEEDBACK: ${{ secrets.DISCORD_URL_FEEDBACK }}
  # variables for discord notifications
  PR_FORMATTED: "${{ format('{{PR #{0} {1} ({2}->{3})}}', github.pull_request.number, github.pull_request.title, github.head_ref, github.base_ref) }}"
  PUSH_FORMATTED: "${{ format('Push to {0}', github.ref) }}"

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ env.PYTHON_TARGET }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_TARGET }}

      - name: Install Python packages, excluding the unnecessary ones
        run: |
          python -m pip install --upgrade pip
          sed -i '/\(tqdm\|gunicorn\|django\-heroku\|uwsgi\)/d' requirements.txt
          pip install -r requirements.txt

      - name: Run pylint
        run: pylint --load-plugins pylint_django tcf_website tcf_core

      - name: Notify that pylint failed
        if: ${{ failure() }}
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_URL_CI }}
        with:
          args: "PR #${{ github.pull_request.number}} ${{ github.pull_request.title }} ($GITHUB_HEAD_REF -> $GITHUB_BASE_REF): pylint failed :("

  django:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12.2
        env:
          POSTGRES_USER: ${{ env.DB_USER}}
          POSTGRES_PASSWORD: ${{ env.DB_PASSWORD }}
          POSTGRES_DB: ${{ env.DB_NAME }}
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ env.PYTHON_TARGET }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_TARGET }}

      - name: Install Python packages, excluding the unnecessary ones
        run: |
          python -m pip install --upgrade pip
          sed -i '/\(pandas\|tqdm\|lint\|autopep8\|gunicorn\|django\-heroku\|uwsgi\)/d' requirements.txt
          pip install -r requirements.txt

      - name: Migrations & Tests
        run: |
          mkdir tcf_website/migrations
          touch tcf_website/migrations/__init__.py
          envsubst < .env.example > .env
          python manage.py makemigrations
          python manage.py migrate
          python manage.py test

      - name: Notify that Django migrations/tests failed
        if: ${{ failure() }}
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_URL_CI }}
        with:
          args: "PR #${{ github.pull_request.number}} ${{ github.pull_request.title }} ($GITHUB_HEAD_REF -> $GITHUB_BASE_REF): Django migrations/tests failed :("

  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install npm packages
        run: npm ci

      - name: Run ESLint
        run: node_modules/.bin/eslint tcf_website/static/**/*.js

      - name: Fail intentionally to see if GitHub Actions Bot works
        run: exit 1

      - name: Notify that eslint failed
        if: ${{ failure() }}
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_URL_CI }}
        with:
          args: ${{ format('ESLint failed :({0}See https://github.com/thecourseforum/theCourseForum2/actions/runs/{1}', '\n', github.run_id) }}

  discord:
    needs: [pylint, django, eslint]
    runs-on: ubuntu-latest
    steps:
      - name: Send a message to tCF Discord Server when triggered by a pull request
        if: ${{ github.event_name == 'pull_request' }}
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_URL_CI }}
        with:
          args: "{{ env.PR_FORMATTED }}: All jobs completed successfully!"

      - name: Send a message to tCF Discord Server when triggered by a push
        if: ${{ github.event_name == 'push' }}
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_URL_CI }}
        with:
          args: "{{ env.PUSH_FORMATTED }}: All jobs completed successfully!"
